spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tstocks
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the database schema
    show-sql: true # Show SQL queries in the console

  data:
    redis:
      host: localhost  # Your Redis server host
      port: 6379 

server:
  port: 8081
